FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o envie-backend cmd/api/main.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/envie-backend .

EXPOSE 8080
CMD ["./envie-backend"]
